spring:
  profiles: default
  banner.location: classpath:banner.txt
  datasource:
    url: jdbc:h2:mem:dataSource
    username: sa
    password:
    driverClassName: org.h2.Driver

server:
  port: 8088
  redirectUri: http://localhost:${server.port}
  apiUri: https://urlshortener8.docs.apiary.io
