spring:
  profiles: default
  banner.location: classpath:banner.txt
  datasource:
    url: jdbc:h2:mem:dataSource
    username: sa
    password:
    driverClassName: org.h2.Driver

version: @project.version@

server:
  port: 80
  redirectUri: http://shortn.er